# Assignment 1
## l1f17bscs0042 
## Umair Talib

## Question 1
### Create a 4X2 integer array and Prints its attributes.

In [63]:
import numpy as np
arr= np.empty([4,2],dtype=int)
print(arr.shape)
print(arr.ndim)
print(arr.dtype)

(4, 2)
2
int32


## Question 2
### Create a 5X2 integer array from a range between 100 to 200 such that the difference between each element is 10.

In [65]:
arr=np.arange(100,200,10)
arr=arr.reshape(5,2)
print(arr)

[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


## Question 3
###  Following is the provided numPy array. return array of items in the third column from all rows. 
### sampleArray = numpy.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])


In [66]:
sampleArray = np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])
arr= sampleArray[:,2]
print(arr)

[33 66 99]


## Question 4
### Return array of odd rows and even columns from below numpy array.
### sampleArray = numpy.array([[3 ,6, 9, 12], [15 ,18, 21, 24], 
### [27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])


In [68]:
sampleArray = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24], 
[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])

print(" ")
arr= sampleArray[1::2,::2]
print(arr)

 
[[15 21]
 [39 45]]


## Querstion 5
### Create a result array by adding the following two NumPy arrays. Next, modify the result array by calculating the square of each element.
### arrayOne = numpy.array([[5, 6, 9], [21 ,18, 27]])
#### arrayTwo = numpy.array([[15 ,33, 24], [4 ,7, 1]])

In [30]:
arrayOne = np.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = np.array([[15 ,33, 24], [4 ,7, 1]])
result =arrayOne+arrayTwo
result= result**2
print(result)

[[ 400 1521 1089]
 [ 625  625  784]]


## Question 6
### Create an 8X3 integer array from a range between 10 to 34 such that the difference between each element is 1 and then Split the array into four equal-sized sub-arrays.

In [34]:
arr=np.arange(10,34,1)
arr1=arr.reshape(8,3)
arr2=np.split(arr1,4)
print(arr2)

[array([[10, 11, 12],
       [13, 14, 15]]), array([[16, 17, 18],
       [19, 20, 21]]), array([[22, 23, 24],
       [25, 26, 27]]), array([[28, 29, 30],
       [31, 32, 33]])]


## Question 7
### Sort following NumPy array first by the second row, then by the second columns.
### sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])


In [41]:
# sorting second row assuming first row sampleArray[0] for simplification
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
##sort second row index=1
result= sampleArray[:,sampleArray[1,:].argsort()]
# sort second column
result1= sampleArray[sampleArray[:,1].argsort(),:]
print(result)
print(" ")
print(result1)

[[73 43 34]
 [12 22 82]
 [66 94 53]]
 
[[82 22 12]
 [34 43 73]
 [53 94 66]]


## Question 8
###  Print max from axis 0 and min from axis 1 from the following 2-D array.
### sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])


In [52]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
result= np.amax(sampleArray,axis=0)
result1= np.amin(sampleArray,axis=1)
print(sampleArray)
print(" ")
print("Max when axis=0 ",result)
print("Min when Axis = 1",result1)


[[34 43 73]
 [82 22 12]
 [53 94 66]]
 
Max when axis=0  [82 94 73]
Min when Axis = 1 [34 12 53]


## Question 9
### Delete the second column from a given array and insert the following new column in its place.
### sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 
### newColumn = numpy.array([[10,10,10]])


In [60]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) 
newColumn = np.array([[10,10,10]])
result=np.delete(sampleArray,1, 1)
result=np.insert(result,1,newColumn,axis=1)
print(result)

[[34 10 73]
 [82 10 12]
 [53 10 66]]
